### ISSUE TITLE
Experiencing  Wrong Scoped Service

### ISSUE THREAD

**Issue by Joe-Effah** [batliwalaa/blazor-fluxor-persistence#1] opened 2024-12-10 08:49 UTC
After Registering the Fluxor Service  and Adding the Presistance Middleware i got this 

`System.AggregateException: 'Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Fluxor.Blazor.Persistence.PersistenceMiddleware Lifetime: Scoped ImplementationType: Fluxor.Blazor.Persistence.PersistenceMiddleware': Cannot consume scoped service 'Microsoft.JSInterop.IJSRuntime' from singleton 'Fluxor.Blazor.Persistence.BrowserStorage.IBrowserStorage'.) 
`
``
![Screenshot 2024-12-10 083702](https://github.com/user-attachments/assets/40647148-e349-43b4-aac3-d719db0c3e0c)
![Screenshot 2024-12-10 083945](https://github.com/user-attachments/assets/2e8e0bfc-d92f-454e-8dac-9c111bb78249)

Please if you can reach out i can show you more details

**Comment by batliwalaa** [comment] 2024-12-11 10:09
Hi Joe,

I'll find some time and have a look at the issue, if you can provide me with skeleton code with issue - it will be easier for me resolve.

Thanks

Kind regards
Anis Batliwala

________________________________
From: Joe ***@***.***>
Sent: Tuesday, December 10, 2024 8:49 AM
To: batliwalaa/blazor-fluxor-persistence ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [batliwalaa/blazor-fluxor-persistence] Experiencing Wrong Scoped Service (Issue #1)


After Registering the Fluxor Service and Adding the Presistance Middleware i got this

System.AggregateException: 'Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Fluxor.Blazor.Persistence.PersistenceMiddleware Lifetime: Scoped ImplementationType: Fluxor.Blazor.Persistence.PersistenceMiddleware': Cannot consume scoped service 'Microsoft.JSInterop.IJSRuntime' from singleton 'Fluxor.Blazor.Persistence.BrowserStorage.IBrowserStorage'.)
``
Screenshot.2024-12-10.083702.png (view on web)<https://github.com/user-attachments/assets/40647148-e349-43b4-aac3-d719db0c3e0c>
Screenshot.2024-12-10.083945.png (view on web)<https://github.com/user-attachments/assets/2e8e0bfc-d92f-454e-8dac-9c111bb78249>

Please if you can reach out i can show you more details

**Comment by batliwalaa** [comment] 2024-12-18 18:54
@Joe-Effah Can you please provide with skeleton code - to reproduce the issue

**Comment by batliwalaa** [comment] 2024-12-23 14:47
Cannot reproduce issue, closing the issue

**Closed as completed by batliwalaa** 2024-12-23 14:47 UTC
